#!/bin/bash
set -euo pipefail
process_file() {
    local file="$1"
    temp_file=$(mktemp)
    expand -t 4 "$file" | sed 's/[[:space:]]*$//' > "$temp_file"
    # sed -i -e :a -e '/^\n*$/{$d;N;ba' -e '}' "$temp_file"
    # sed -i '/^$/N;/^\n$/D' "$temp_file"
    sed -i 's/ \+\t/\t/g' "$temp_file"
    if ! cmp -s "$temp_file" "$file"; then
        mv "$temp_file" "$file"
        echo "fixed whitespace in $file"
    else
        rm "$temp_file"
    fi
}
files=*.[ch]
for file in $files; do
    process_file "$file"
done

jscpd $files

cppcheck --enable=all --suppress=postfixOperator --suppress=syntaxError:Utilities.hpp --suppress=unusedStructMember:ProgramTemperatureCalibration.hpp --suppress=useStlAlgorithm:ProgramBase.hpp --suppress=missingIncludeSystem --std=c++21 $files

egrep -n '^[^/].*[^ ] {2,}[^ ]' $files | egrep -v '^\s*\/\/'
